sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_81ecd96a313f_key -iv $encrypted_81ecd96a313f_iv -in marine-set-350105-bef34c7b93fa.json.enc -out marine-set-350105-bef34c7b93fa.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file marine-set-350105-bef34c7b93fa.json
  - gcloud config set project marine-set-350105 
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials shoppings-cluster
  
script:
  - docker run -e CI=true ubuntu

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
