apiVersion: batch/v1
kind: Job
metadata:
  name: job-ecommerce
spec:
  template:
    spec:
      containers:
      - name: job-django
        image: us-central1-docker.pkg.dev/extended-cinema-334708/image-repo/shopping:v1
        command: 
         - bash
         - -c
         - python3 manage.py makemigrations  &&
           python3 manage.py migrate 

      restartPolicy: Never
