apiVersion: v1
kind: Pod
metadata:
  name: jobpod
spec:
  containers:
   - name: podjango
     image: us-central1-docker.pkg.dev/extended-cinema-334708/image-repo/shopping:v1
     ports:
      - containerPort: 9001
     imagePullPolicy: Always
     env:
      - name: DJANGO_SUPERUSER_PASSWORD
        value: ruckus
      - name: DJANGO_SUPERUSER_EMAIL
        value: bansalsahil227@gmail.com
      - name: DJANGO_SUPERUSER_USERNAME
        value: admin
      - name: MYSQL_PASSWORD
        value: password1
      - name: MYSQL_DATABASES
        value: ecommerce_database
      - name: MYSQL_HOST
        value: sql-cluster-ip-service
  restartPolicy: OnFailure