apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volumes
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sahil/Desktop/sqldatas/"
