apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volumes
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector: 
    matchLabels: 
      type: local
     