apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sql-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 0
  selector:
    matchLabels:
      database: mysql
  template:
    metadata:
      labels:
        database: mysql
    spec:
      
      containers:
       - name: db
         image: us-central1-docker.pkg.dev/extended-cinema-334708/image-repo/shoppingdb:v1
         ports:
          - containerPort: 3306
         imagePullPolicy: Always
         
         
            
         
         env:
          - name: MYSQL_PASSWORD
            value: "'password1'"
          - name: MYSQL_DATABASES
            value: ecommerce_database
          - name: MYSQL_ROOT_PASSWORD
            value: password2

          - name: MYSQl_COMMAND_PASSWORD
            value:  password1